const WORDS = [
  "apple","arrow","atlas","amber","angel","aspen","azure","acorn","adobe","agave",
  "album","alley","alpha","ample","ankle","anvil","aroma","ashen","audit","avian",
  "bacon","badge","baker","balm","bamboo","banjo","baron","basin","beach","beard",
  "beast","berry","birch","blade","blaze","bliss","bloom","board","bonus","booth",
  "bound","brain","brass","brave","bread","brick","brisk","brook","brush","build",
  "bunch","cabin","camel","candy","cargo","cedar","chalk","charm","chase","chess",
  "chief","choir","chord","cider","claim","clash","clerk","cliff","climb","clock",
  "cloud","clown","coach","coast","cobra","cocoa","comet","coral","cover","craft",
  "crane","crash","creek","crest","crisp","cross","crown","crush","curve","cycle",
  "daisy","dance","delta","depth","derby","diary","digit","diver","dodge","dolphin",
  "donor","draft","drain","dream","drift","drink","drive","drums","dusk","dwarf",
  "eagle","earth","ember","enter","equal","event","every","exalt","extra","fable",
  "fairy","faith","fancy","feast","fence","ferry","fiber","field","flame","flash",
  "flask","fleet","flint","float","flock","flood","floor","flour","fluid","flute",
  "focal","foggy","force","forge","forth","forum","found","frame","fresh","front",
  "frost","fruit","fudge","fungi","gamer","gamma","gauge","gavel","ghost","giant",
  "giddy","glade","glare","glass","gleam","glide","globe","gloom","glory","glove",
  "goose","grace","grade","grain","grand","grape","graph","grasp","grass","gravel",
  "green","grind","grove","guard","guest","guide","guild","guise","gulch","gummy",
  "habit","happy","hardy","haven","hazel","heart","hedge","heist","heron","honey",
  "honor","horse","hotel","house","husky","hydro","icing","igloo","image","inbox",
  "index","inner","input","intro","ionic","ivory","jewel","joker","jolly","juice",
  "jumbo","karma","kayak","knack","kneel","knife","knoll","koala","label","lager",
  "lance","laser","latch","layer","leach","leafy","learn","lemon","level","lever",
  "light","lilac","limit","linen","liver","llama","lobby","lofty","logic","lotus",
  "lunar","lunch","lyric","macro","magic","manor","maple","march","marsh","mason",
  "match","mayor","medal","melon","mercy","metal","meter","midst","miner","minor",
  "mirth","model","money","moose","morph","motto","mound","mount","mouse","mural",
  "naive","nectar","nerve","noble","north","notch","novel","nurse","oasis","ocean",
  "olive","omega","onset","opera","orbit","order","organ","otter","outer","oxide",
  "ozone","paddy","paint","panda","panel","paper","party","paste","patch","pearl",
  "pedal","penny","perch","piano","pilot","pinch","pixel","pizza","place","plaid",
  "plain","plane","plant","plate","plaza","plumb","plume","point","poker","polar",
  "poppy","porch","poser","pouch","power","press","pride","prime","print","prism",
  "prize","probe","prose","proud","proxy","prune","pulse","pupil","purse","quail",
  "qualm","quart","queen","query","quest","quiet","quill","quirk","quota","quote",
  "radar","radio","rainy","rally","ranch","range","rapid","raven","razor","reach",
  "rebel","reign","relay","remix","ridge","rifle","river","robin","robot","rocky",
  "rodeo","royal","rugby","rumor","rural","sable","saint","salad","salon","salsa",
  "sandy","satin","sauna","savor","scale","scare","scene","scent","scope","scout",
  "serif","shark","sharp","sheet","shell","shelf","shift","shine","shirt","shock",
  "shore","shrub","siege","sigma","silky","siren","skull","slate","slide","slope",
  "smart","smile","smoke","snail","snake","solar","sonic","south","space","spark",
  "spear","spice","spike","spine","spoke","spoon","sport","spray","squad","stack",
  "staff","stage","stain","stake","stalk","stamp","stand","start","stash","steam",
  "steel","steep","steer","stern","stick","still","sting","stock","stomp","stone",
  "stool","storm","story","stove","strap","straw","strip","strut","study","stump",
  "style","sugar","suite","sunny","surge","swamp","swarm","sweet","swept","swift",
  "swing","sworn","syrup","table","talon","tango","taper","taste","tempo","terra",
  "theme","thick","thorn","thump","tidal","tiger","timer","toast","token","topaz",
  "torch","total","tower","trace","track","trade","trail","train","trait","tramp",
  "trash","treat","trend","trial","tribe","trick","troop","trout","truck","truly",
  "trunk","trust","tulip","tundra","tunic","turbo","tutor","tweed","twice","twist",
  "ultra","umbra","unity","upper","urban","usher","usual","utter","vague","valid",
  "value","valve","vapor","vault","velvet","venue","verse","vigor","viper","viral",
  "vista","vital","vivid","vocal","voice","voter","vowel","wagon","waltz","watch",
  "water","weave","wedge","whale","wheat","wheel","while","whirl","white","whole",
  "width","wield","windy","witch","world","worry","wound","wrath","wrist","yacht",
  "yield","youth","zebra","zesty","bloom","spark","crest","flame","drift","grove",
  "haven","jewel","knack","lofty","maple","noble","ocean","pearl","quest","ridge",
  "shine","tower","unity","vivid","waltz","amber","blaze","charm","delta","ember",
  "frost","gleam","honor","ivory","jolly","karma","lunar","mercy","north","olive",
  "plume","quill","raven","solar","thorn","ultra","vault","whale","yield","azure",
  "brass","cliff","dawn","eagle","fiber","glade","husky","inlet","joust","kneel",
  "lance","moose","nexus","orbit","prism","quart","robin","surge","trout","usher",
  "vigor","wheat","xenon","yacht","zonal","abode","blend","crane","dwarf","epoch",
  "flint","grail","haste","irony","jaunt","knoll","latch","mirth","noble","oasis",
  "plaid","quota","rural","stoic","truce","unify","verse","wield","xerox","yearn",
  "agile","bower","cloak","ditto","elfin","forge","grout","hinge","ionic","jazzy",
  "kudos","llama","mocha","nifty","optic","plush","queue","recap","sworn","talon",
  "udder","vouch","whisk","yodel","zilch","adept","brink","civil","dodge","ensue",
  "flair","gnash","haven","imbue","juror","kebab","lucid","mogul","notch","outdo",
  "patio","quake","repel","savor","terse","usurp","valor","wrath","yearn","zephyr",
  "align","bluff","clasp","drape","elbow","flank","grasp","hover","inept","jumpy",
  "kinky","lever","mango","nudge","omega","pluck","quash","roost","stave","twine",
  "unpin","venom","wager","xylem","yucca","zippy","annex","brood","chant","dwell",
  "evade","frisk","glint","hedge","infer","joker","knead","lunge","mimic","notch",
  "onset","plumb","quirk","rinse","swirl","thaw","untie","vinyl","whack","alloy",
  "botch","creed","dizzy","elude","fjord","groom","hover","islet","jaunt","kelp",
  "lyric","marsh","nervy","ovoid","plait","regal","shawl","tepid","undue","vivid",
  "wince","abbot","blurt","caulk","dwelt","exude","fetid","gouge","heath","ileum",
  "jetty","knave","liege","moult","natal","oxide","qualm","rebut","shunt","taboo",
  "usurp","voila","wrung","elfin","gusto","hoard","ivory","jumbo","knack","lusty"
];

export function generateGameName() {
  const picked = [];
  for (let i = 0; i < 3; i++) {
    const index = Math.floor(Math.random() * WORDS.length);
    picked.push(WORDS[index].charAt(0).toUpperCase() + WORDS[index].slice(1));
  }
  return picked.join(" ");
}

export default WORDS;
